apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer
  labels:
    app: beer
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: beer
  template:
    metadata:
      labels:
        app: beer
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: beer
          image: beer-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: false
